version: '3.9'
services:
  bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: e2e
    networks:
      - bot-network-test
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  database:
    image: mongo
    hostname: mongo
    container_name: remember-notes-test-db
    command: mongod --auth
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - dbdata-test:/data/db
      - "$PWD/mongo-entrypoint/entrypoint.js:/docker-entrypoint-initdb.d/entrypoint.js:ro"
    ports:
      - "27017-27019:27017-27019"
    networks:
      - bot-network-test
networks:
  bot-network-test:
    driver: bridge
volumes:
  dbdata-test:
    driver: local