version: '3.9'
services:
  bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    networks:
      - bot-network
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  database:
    image: mongo
    hostname: mongo
    env_file:
      - .env
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - bot-network
networks:
  bot-network:
    driver: bridge
volumes:
  dbdata: